sudo: required
services:
  - docker

before_install:
  - docker build -t mikhailadriaanse/docker-react -f Dockerfile.dev .

script: 
  - docker run mikhailadriaanse/docker-react npm run test -- --coverage